Repository mbti-builder/fe, pull requests merged in 2021-09, with the labels that each got.

#3 typescript 스캐폴딩
  babel.config.json
  config/webpack/webpack.base.js
  package-lock.json
  package.json
  src/app.ts
  src/components/Bye.ts
  src/components/Hi.ts
  src/index.ts
  tsconfig.json
Labels: environment

#2 scss 스캐폴딩
  babel.config.json
  config/webpack/webpack.base.js
  config/webpack/webpack.dev.js
  config/webpack/webpack.prod.js
  package-lock.json
  package.json
  src/app.ts
  src/components/Bye.ts
  src/components/Hi.ts
  src/index.ts
  src/styles/index.css
  src/styles/index.scss
  src/styles/main.scss
  tsconfig.json
Labels: environment

#1 github, npm, webpack 스캐폴딩
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  babel.config.json
  config/webpack/webpack.base.js
  config/webpack/webpack.dev.js
  config/webpack/webpack.prod.js
  package-lock.json
  package.json
  public/index.html
  src/app.ts
  src/components/Bye.ts
  src/components/Hi.ts
  src/index.ts
  src/styles/index.scss
  src/styles/main.scss
  tsconfig.json
Labels: environment

#7 classnames 모듈 설치 및 scss mixin 추가
  package-lock.json
  package.json
  src/styles/_mixin.scss
  src/styles/index.scss
Labels: environment

#6 Storybook을 사용할 수 있도록 기본 설정
  .storybook/main.js
  .storybook/preview.js
  .storybook/webpack.config.js
  package-lock.json
  package.json
  src/App.stories.tsx
  src/styles/_mixin.scss
  src/styles/index.scss
Labels: environment

#4 Prettier & ESLint 기본 설정
  .eslintignore
  .eslintrc
  .prettierrc
  .vscode/settings.json
  package-lock.json
  package.json
Labels: environment

#9 빌드 및 테스트에 대한 CI 설정
  .github/workflows/CI.yml
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  src/App.test.tsx
Labels: environment

#5 React를 사용할 수 있도록 기본 설정
  .github/workflows/CI.yml
  .storybook/main.js
  .storybook/preview.js
  .storybook/webpack.config.js
  babel.config.json
  config/webpack/webpack.base.js
  config/webpack/webpack.dev.js
  config/webpack/webpack.prod.js
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  public/index.html
  src/App.stories.tsx
  src/App.test.tsx
  src/App.tsx
  src/app.ts
  src/components/Bye.ts
  src/components/Hi.ts
  src/index.ts
  src/index.tsx
  src/styles/_mixin.scss
  src/styles/index.scss
  tsconfig.json
Labels: environment

#13 컴포넌트 테스트 스캐폴딩
  .vscode/gwt.code-snippets
  src/App.test.tsx
  src/test-utils.tsx
Labels: environment

#10 lint --fix가 적용되도록 처리
  .eslintignore
  .eslintrc
  config/webpack/webpack.base.js
  config/webpack/webpack.dev.js
  config/webpack/webpack.prod.js
  jest.config.js
  package-lock.json
  package.json
  src/App.test.tsx
  src/App.tsx
  src/index.tsx
Labels: environment

#15 jest 에서 scss의 @ 키워드에 대한 에러 해결
  jest.config.js
  package-lock.json
  package.json
Labels: environment

#17 storybook에서 redux를 사용할 수 있도록 한다
  .storybook/preview.js
  .storybook/webpack.config.js
Labels: environment

#16 Webpack에서 공통되는 부분을 base config로 옮김
  config/webpack/webpack.base.js
  config/webpack/webpack.dev.js
  config/webpack/webpack.prod.js
Labels: environment

#11 Redux 환경설정을 한다
  .eslintrc
  .storybook/preview.js
  .storybook/webpack.config.js
  .vscode/gwt.code-snippets
  babel.config.json
  config/webpack/webpack.base.js
  config/webpack/webpack.dev.js
  config/webpack/webpack.prod.js
  jest.config.js
  package-lock.json
  package.json
  src/App.stories.tsx
  src/App.test.tsx
  src/App.tsx
  src/index.tsx
  src/store/index.ts
  src/store/uiSlice.test.ts
  src/store/uiSlice.ts
  src/test-utils.tsx
Labels: environment

#18 scss 절대경로 설정 및 variable, mixin 등 scss를 기본으로 import 하도록 설정
  .storybook/webpack.config.js
  config/webpack/webpack.dev.js
  config/webpack/webpack.prod.js
Labels: environment

#19 doodlin design system을 참고하여 mixin과 variable을 추가
  src/index.tsx
  src/styles/_color.scss
  src/styles/_mixin.scss
  src/styles/_variable.scss
  src/styles/index.scss
  src/styles/main.scss
Labels: environment

#20 공통으로 사용될 Button 컴포넌트 제작
  src/App.tsx
  src/atom/Button/Button.scss
  src/atom/Button/Button.stories.tsx
  src/atom/Button/Button.test.tsx
  src/atom/Button/index.tsx
Labels: feature

#29 ESLint의 react/jsx-props-no-spreading 설정을 off 한다
  .eslintrc
Labels: environment

#26 공통으로 사용될 Icon 컴포넌트 제작
  src/atom/Icon/Icon.scss
  src/atom/Icon/Icon.stories.tsx
  src/atom/Icon/Icon.test.tsx
  src/atom/Icon/index.tsx
  src/styles/index.scss
Labels: feature

#27 공통으로 사용될 Input 컴포넌트 제작
  src/atom/Input/Input.scss
  src/atom/Input/Input.stories.tsx
  src/atom/Input/Input.test.tsx
  src/atom/Input/index.tsx
Labels: feature

#28 스토리북 continuous deploy용 action을 추가
  .github/workflows/STORYBOOK_CD.yml
Labels: environment

#35 공통으로 사용될 Text 컴포넌트 추가
  jest.config.js
  src/App.tsx
  src/atom/Text/Text.scss
  src/atom/Text/Text.stories.tsx
  src/atom/Text/Text.test.tsx
  src/atom/Text/index.tsx
  src/styles/_variable.scss
  src/styles/index.scss
Labels: feature

#30 프로젝트에 react-router-dom 설정
  .storybook/preview.js
  package-lock.json
  package.json
  src/App.test.tsx
  src/App.tsx
  src/index.tsx
  src/pages/LandingPage/LandingPage.test.tsx
  src/pages/LandingPage/index.tsx
Labels: environment

#36 Button 컴포넌트 테스트 정상화 및 shadow props 추가
  src/atom/Button/Button.scss
  src/atom/Button/Button.stories.tsx
  src/atom/Button/Button.test.tsx
  src/atom/Button/index.tsx
  src/atom/Icon/Icon.test.tsx
  src/atom/Input/Input.stories.tsx
  src/atom/Input/Input.test.tsx
  src/styles/_color.scss
  src/styles/_variable.scss
Labels: refactor

#37 공통으로 사용될 Spinner 컴포넌트 제작
  @types/custom-types/index.d.ts
  src/atom/Spinner/Spinner.scss
  src/atom/Spinner/Spinner.stories.tsx
  src/atom/Spinner/Spinner.test.tsx
  src/atom/Spinner/index.tsx
Labels: feature

#34 공통으로 사용될 Skeleton 컴포넌트 제작
  src/atom/Skeleton/Skeleton.scss
  src/atom/Skeleton/Skeleton.stories.tsx
  src/atom/Skeleton/Skeleton.test.tsx
  src/atom/Skeleton/index.tsx
  src/atom/Spinner/Spinner.scss
  src/atom/Spinner/Spinner.stories.tsx
  src/atom/Spinner/Spinner.test.tsx
  src/atom/Spinner/index.tsx
Labels: feature

#33 사용자 정의 타입들을 관리하는 index.d.ts 추가
  .eslintignore
  .eslintrc
  @types/custom-types/index.d.ts
  src/atom/Button/index.tsx
  src/atom/Skeleton/Skeleton.scss
  src/atom/Skeleton/Skeleton.stories.tsx
  src/atom/Skeleton/Skeleton.test.tsx
  src/atom/Skeleton/index.tsx
  src/atom/Spinner/Spinner.scss
  src/atom/Spinner/Spinner.stories.tsx
  src/atom/Spinner/Spinner.test.tsx
  src/atom/Spinner/index.tsx
  tsconfig.json
Labels: environment

#40 공통으로 사용될 ToastView 컴포넌트 추가
  src/atom/Text/Text.scss
  src/atom/Text/index.tsx
  src/atom/ToastView/ToastView.scss
  src/atom/ToastView/ToastView.stories.tsx
  src/atom/ToastView/ToastView.test.tsx
  src/atom/ToastView/index.tsx
  src/hooks/useToast.tsx
  src/pages/LandingPage/index.tsx
  src/styles/_mixin.scss
  src/styles/_variable.scss
Labels: feature

#38 공통으로 사용될 Modal 컴포넌트 제작
  public/index.html
  src/atom/Button/Button.scss
  src/atom/Modal/Modal.scss
  src/atom/Modal/Modal.stories.tsx
  src/atom/Modal/Modal.test.tsx
  src/atom/Modal/index.tsx
  src/atom/Skeleton/Skeleton.scss
  src/atom/Skeleton/Skeleton.stories.tsx
  src/atom/Skeleton/Skeleton.test.tsx
  src/atom/Skeleton/index.tsx
  src/hooks/useModal.tsx
  src/styles/_variable.scss
Labels: feature

#42 함수식, Storybook Arg 관련 리팩터링
  src/atom/Button/Button.stories.tsx
  src/atom/Button/Button.test.tsx
  src/atom/Icon/Icon.stories.tsx
  src/atom/Icon/Icon.test.tsx
  src/atom/Input/Input.stories.tsx
  src/atom/Input/Input.test.tsx
  src/atom/Skeleton/Skeleton.stories.tsx
  src/atom/Skeleton/Skeleton.test.tsx
  src/atom/Spinner/Spinner.stories.tsx
  src/atom/Spinner/Spinner.test.tsx
  src/atom/Text/Text.scss
  src/atom/Text/Text.stories.tsx
  src/atom/Text/index.tsx
Labels: refactor
